export interface BusinessReplyStatusMetric {
  label: string;
  value: number;
  detail: string;
}

export interface BusinessReplyStatusSnapshot {
  lastUpdated: string;
  sourcePath: string;
  summary: string;
  metrics: BusinessReplyStatusMetric[];
  nextStep: string;
  boundary: string;
}

// Generated by scripts/build-cityatlas-business-reply-status.mjs from docs/seo-aeo-geo/CITYATLAS_BUSINESS_REPLY_STATUS.md.
// Do not edit this file by hand. Update the source doc, then rerun the generator.
export const businessReplyStatusSnapshot: BusinessReplyStatusSnapshot = {
  "lastUpdated": "2026-06-25",
  "sourcePath": "docs/seo-aeo-geo/CITYATLAS_BUSINESS_REPLY_STATUS.md",
  "summary": "CityAtlas has already reviewed 7 real inbound business replies, sent 3 live follow-ups where the intent was clear, and kept the first step on the free-review path.",
  "metrics": [
    {
      "label": "Inbound replies reviewed",
      "value": 7,
      "detail": "Messages read and triaged from real businesses."
    },
    {
      "label": "Live replies sent",
      "value": 3,
      "detail": "Clear follow-ups already sent by CityAtlas."
    },
    {
      "label": "Active conversations",
      "value": 2,
      "detail": "Businesses still in a real back-and-forth now."
    },
    {
      "label": "Hosted-offer asks made",
      "value": 2,
      "detail": "Hosted meal or service asks already made when the fit was clear."
    }
  ],
  "nextStep": "The next move is still a fit note, short call, or hosted visit only when the match is clear.",
  "boundary": "Reply only when the business clearly asks for details, shows interest, redirects to a better contact, asks about pricing, or declines. Do not reply to autoresponders, signatures only, or unclear intent. Nothing public or paid goes live from the first reply alone, and CityAtlas can still say the fit is weak."
};

